VideoGameMarket/VideoGameMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import accounts.views
from games import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', views.home, name="home"),
    url(r'^games/', include('games.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

VideoGameMarket/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name = 'signup'),
    url(r'^login/', views.loginView, name = 'login'),
    url(r'^logout/', views.logoutView, name = 'logout'),
]

VideoGameMarket/games/urls.py
from django.conf.urls import url
from . import views

app_name = 'games'

urlpatterns = [
    url(r'^search/', views.search, name = 'search'),
    url(r'^accountSettings/', views.accountSettings, name = 'accountSettings'),
    url(r'^orderHistory/', views.orderHistory, name = 'orderHistory'),
    url(r'^gameDetails/(?P<game_id>[0-9]+)/$', views.gameDetails, name = 'gameDetails'),
    url(r'^purchaseGame/(?P<game_id>[0-9]+)/$', views.purchaseGame, name = 'purchaseGame'),
]

VideoGameMarket/accounts/models.py
from django.db import models

# Create your models here.

VideoGameMarket/games/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class Game(models.Model):
    title = models.CharField(max_length = 250)
    pub_date = models.DateTimeField()
    description = models.TextField()
    price = models.DecimalField(max_digits = 5, decimal_places = 2)
    image = models.ImageField(upload_to= 'media/')

    platforms_choices = (
        ('xbox', 'XBOX ONE'),
        ('playstation', 'Playstation 4'),
        ('Nintendo', 'Nintendo Switch'),
        ('PC', 'PC'),
    )
    platform = models.CharField(
        max_length=30,
        choices= platforms_choices,
        default='PC',
    )

    def __str__(self):
        return self.title

    def summary(self):
        return self.description[:60]


class Order(models.Model):
    pub_date = models.DateTimeField()
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

VideoGameMarket/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return render(request,'home',{'auth':"you are already logged in"})

    if request.method == "POST":
        #create User
        if request.POST['password1'] == request.POST['password2']:
            try:
                testUser = User.objects.get(username = request.POST['username'])
                return render(request,'accounts/signup.html', {'error': 'Username has already been taken'})

            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password = request.POST['password1'], email = request.POST['email'])
                login(request, user)
                return redirect('home')
        else:
            return render(request,'accounts/signup.html', {'error': 'Passwords didn\'t match'})
    else:
        return render(request,'accounts/signup.html')


def loginView(request):
    if request.user.is_authenticated:
        return render(request,'games/home.html',{'auth':"you are already logged in"})

    if request.method == "POST":
        request.POST['password']
        user = authenticate(username = request.POST['username'], password = request.POST['password'])
        if user is not None:
            login(request, user)
            #redirect to success page
            return redirect('home')

        else:
            return render(request,'accounts/login.html',{'error' : 'The Username and password didn\'t match' })
    else:
        return render(request,'accounts/login.html')


def logoutView(request):
    print("TESTIIIING")
    if request.method == "POST":
        logout(request)
        return redirect('home')

VideoGameMarket/games/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Game, Order
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.utils import timezone

# Create your views here.
def home(request):
    games = Game.objects.order_by('pub_date')
    return render(request, 'games/home.html', {'games':games})


def gameDetails(request, game_id):
    game = Game.objects.get(pk = game_id)
    return render(request, 'games/gameDetails.html', {'game':game})

def search(request):
    if request.method == "POST":
        searchQuery = request.POST['search']
    else:
        searchQuery = ''
    games = Game.objects.raw('Select * FROM games_game WHERE title LIKE "%'+searchQuery+'%"')
    return render(request, 'games/search.html', {'games':games, 'searchQuery':searchQuery})

def purchaseGame(request,game_id):
    #need to check that user is logged in if request.user.is_authenticated():
    if request.user.is_authenticated:
        game = Game.objects.get(pk =game_id)
        order = Order(pub_date = timezone.datetime.now(), buyer = request.user,game = game)
        order.save()
        return orderHistory(request,True)

    else:
        games = Game.objects.order_by('pub_date')
        return render(request, 'games/home.html', {'games':games, 'error': 'You need to be logged in to purchase a game'})

def accountSettings(request):
    return render(request, 'games/account.html',{'name':request.user.username})


def orderHistory(request, purchasedGame = None):
    orders = Order.objects.order_by('pub_date').filter( buyer = request.user.id)
    games = []
    total = 0
    for order in orders:
        game = Game.objects.get(pk = order.game_id)
        game.pub_date = order.pub_date
        total+= game.price
        games.append(game)
    games = games[::-1]
    if total != 0:
        if purchasedGame:
            return render(request, 'games/orderHistory.html', {'games':games, 'total':total,'thanks':'Thank you for buying with us'})
        else:
            return render(request, 'games/orderHistory.html', {'games': games, 'total': total})

    else:
        return render(request, 'games/orderHistory.html', {'games':games})

VideoGameMarket/accounts/templates/accounts/login.html
{%extends 'base.html'%}

{% block content %}
<style>
    html, body {
        width: 100%;
        height: 100%;
        font-family: "Helvetica Neue", Helvetica, sans-serif;
        color: #444;
        -webkit-font-smoothing: antialiased;;
    }
    img {
    max-width: 90%;
    max-height: 90%;
  }
    #container {
        width: 340px;
        height: 363px;
        top: 30%;
        left: 50%;
        margin-top: 5%;
        margin-left: 40%;
        background: #fff;
        border-radius: 3px;
        border: 1px solid #ccc;
        box-shadow: 0 1px 2px rgba(0, 0, 0, .1);
    }
    form {
        margin: 0 auto;
        margin-top: 20px;
    }
    label {
        color: #555;
        display: inline-block;
        margin-left: 18px;
        padding-top: 10px;
        font-size: 14px;
    }
    p a {
        font-size: 11px;
        color: #aaa;
        float: right;
        margin-top: -13px;
        margin-right: 20px;
        -webkit-transition: all .4s ease;
        -moz-transition: all .4s ease;
        transition: all .4s ease;
    }
    p a:hover {
        color: #903939;
    }
    input {
        font-family: "Helvetica Neue", Helvetica, sans-serif;
        font-size: 12px;
        outline: none;
    }
    #lower {
        background: #ecf2f5;
        width: 100%;
        height: 58px;
        margin-top: 15px;
    }
    input[type=checkbox] {
        margin-left: 20px;
        margin-top: 30px;
    }
    .check {
        margin-left: 3px;
    }
    input[type=submit] {
        float: right;
        margin-right: 20px;
        margin-top: 20px;
        width: 80px;
        height: 30px;
    }
    input[type=submit] {
        float: right;
        margin-right: 20px;
        margin-top: 20px;
        width: 80px;
        height: 30px;
        font-size: 14px;
        font-weight: bold;
        color: #fff;
        background-color: #acd6ef; /*IE fallback*/
        background-image: -webkit-gradient(linear, left top, left bottom, from(#0a0404), to(#903939));
        background-image: -moz-linear-gradient(top left 90deg, #acd6ef 0%, #FF4500 100%);
        background-image: linear-gradient(top left 90deg, #acd6ef 0%, #6ec2e8 100%);
        border-radius: 30px;
        border: 1px solid #66add6;
        box-shadow: 0 1px 2px rgba(0, 0, 0, .3), inset 0 1px 0 rgba(255, 255, 255, .5);
        cursor: pointer;
    }
    input[type=text],
    input[type=password] {
        color: #777;
        padding-left: 10px;
        margin: 10px;
        margin-top: 12px;
        margin-left: 18px;
        width: 290px;
        height: 35px;
        border: 1px solid #c7d0d2;
        border-radius: 2px;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #f5f7f8;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #f5f7f8;
        -webkit-transition: all .4s ease;
        -moz-transition: all .4s ease;
        transition: all .4s ease;
    }
    input[type=text]:hover,
    input[type=password]:hover {
        border: 1px solid #903939;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .7), 0 0 0 5px #903939;
    }
    input[type=text]:focus,
    input[type=password]:focus {
        border: 1px solid #FF4500;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #FF4500;
    }
</style>




<div id="container">
    <img src="http://i65.tinypic.com/25s4ho7.png" border="0" >
    {% if error %}
    {{ error }}
    {% endif %}
    <form method="POST" action="{% url 'accounts:login' %}">
        {% csrf_token %}

        <label for="username">Username:</label>

        <input type="text" id="username" name="username">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        <div id="lower">
            <label for="checkbox">forgot password</label>
            <input type="submit" value="Login">
        </div><!--/ lower-->
    </form>
</div>





{% endblock %}

VideoGameMarket/accounts/templates/accounts/signup.html
{%extends 'base.html'%}

{% block content %}


{%if error%}
{{error}}
<br / >
<br / >
{% endif %}

<style>
    html, body {
        width: 100%;
        height: 100%;
        font-family: "Helvetica Neue", Helvetica, sans-serif;
        color: #444;
        -webkit-font-smoothing: antialiased;;
    }
    #container {
        width: 340px;
        height: 640px;
        top: 30%;
        left: 50%;
        margin-top: 5%;
        margin-left: 40%;
        background: #fff;
        border-radius: 3px;
        border: 1px solid #ccc;
        box-shadow: 0 1px 2px rgba(0, 0, 0, .1);
    }
    form {
        margin: 0 auto;
        margin-top: 20px;
    }
    label {
        color: #555;
        display: inline-block;
        margin-left: 18px;
        padding-top: 10px;
        font-size: 14px;
    }
    img {
    max-width: 90%;
    max-height: 90%;
  }
    p a {
        font-size: 11px;
        color: #aaa;
        float: right;
        margin-top: -13px;
        margin-right: 20px;
        -webkit-transition: all .4s ease;
        -moz-transition: all .4s ease;
        transition: all .4s ease;
    }
    p a:hover {
        color:#903939;
    }
    input {
        font-family: "Helvetica Neue", Helvetica, sans-serif;
        font-size: 12px;
        outline: none;
    }
    #lower {
        background: #ecf2f5;
        width: 100%;
        height: 58px;
        margin-top: 15px;
    }
    input[type=checkbox] {
        margin-left: 20px;
        margin-top: 30px;
    }
    .check {
        margin-left: 3px;
    }
    input[type=submit] {
        float: right;
        margin-right: 20px;
        margin-top: 20px;
        width: 80px;
        height: 30px;
    }
    input[type=submit] {
        float: right;
        margin-right: 20px;
        margin-top: 20px;
        width: 80px;
        height: 30px;
        font-size: 14px;
        font-weight: bold;
        color: #fff;
        background-color: #acd6ef; /*IE fallback*/
        background-image: -webkit-gradient(linear, left top, left bottom, from(#0a0404), to(#903939));
        background-image: -moz-linear-gradient(top left 90deg, #acd6ef 0%, #FF4500 100%);
        background-image: linear-gradient(top left 90deg, #acd6ef 0%, #6ec2e8 100%);
        border-radius: 30px;
        border: 1px solid #66add6;
        box-shadow: 0 1px 2px rgba(0, 0, 0, .3), inset 0 1px 0 rgba(255, 255, 255, .5);
        cursor: pointer;
    }
    input[type=text],
    input[type=password] {
        color: #777;
        padding-left: 10px;
        margin: 10px;
        margin-top: 12px;
        margin-left: 18px;
        width: 290px;
        height: 35px;
        border: 1px solid #c7d0d2;
        border-radius: 2px;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #f5f7f8;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #f5f7f8;
        -webkit-transition: all .4s ease;
        -moz-transition: all .4s ease;
        transition: all .4s ease;
    }
    input[type=text]:hover,
    input[type=password]:hover {
        border: 1px solid #903939;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .7), 0 0 0 5px #903939;
    }
    input[type=text]:focus,
    input[type=password]:focus {
        border: 1px solid #FF4500;
        box-shadow: inset 0 1.5px 3px rgba(190, 190, 190, .4), 0 0 0 5px #FF4500;
    }
</style>


<div id="container">
    <img src="http://i65.tinypic.com/25s4ho7.png" border="0" >
    <form method="POST" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        <!-- {% if userForm.errors %}
        {% for field in userForm %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <p style="color: red"><strong>{{ error|escape }}</strong></p>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in userForm.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %} -->
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password1">
        <label for="password">Confirm password:</label>
        <input type="password" id="password" name="password2">
        <label for="username">Shipping Address:</label>
        <input type="text" id="shipping" name="shipping">
        <div id="lower">
            <input type="submit" value="Sign Up">
        </div><!--/ lower-->

    </form>
</div>



{% endblock %}

VideoGameMarket/games/templates/games/buyCart.html
<html>
    <head>
        <title>Buy Game</title>
    </head>
</html>

VideoGameMarket/games/templates/games/home.html
{%extends 'base.html'%}

{% block content %}

{%if auth%}
{{auth}}
<br / >
<br / >
{% endif %}

<style>
  .wrapper {
    width: 68em;
    margin: 4em auto;
    background: #fff;
    padding: 4em;
    border-radius: 8px;
    border: 1px solid #f5f5f5;
  }

  }
  code {
    padding: .2em .3em;
    background: #f5f5f5;
    margin: 0 .2em;
    border-radius: 4px;
    font-size: .95em;
    font-family: 'Source Code Pro';
  }
  .product-grid.product-grid--flexbox .product-grid__wrapper {
    display: flex;
    flex-wrap: wrap;
  }
  .product-grid.product-grid--flexbox .product-grid__title {
    height: auto;
  }
  .product-grid.product-grid--flexbox .product-grid__title:after {
    display: none;
  }
  .product-grid__wrapper {
    margin-left: -1rem;
    margin-right: -1rem;
  }
  .product-grid__product-wrapper {
    padding: 1rem;
    float: left;
    width: 33.33333%;
  }
  .product-grid__product {
    padding: 1rem;
    position: relative;
    cursor: pointer;
    background: #fff;
    border-radius: 4px;
    box-shadow: 0px 0px 0px 1px #eee
  }
  .product-grid__product:hover {
    box-shadow: 0px 0px 0px 1px #eee;
    z-index: 50;
  }
  .product-grid__product:hover .product-grid__extend {
    display: block;
  }
  .product-grid__img-wrapper {
    width: 100%;
    text-align: center;
    padding-top: 1rem;
    padding-bottom: 1rem;
    height: 150px;
  }
  .product-grid__img {
    max-width: 100%;
    height: auto;
    max-height: 100%;
  }
  .product-grid__title {
    margin-top: .875rem;
    display: block;
    font-size: 1.125em;
    color: #222;
    height: 3em;
    overflow: hidden;
    position: relative;
  }
  .product-grid__title:after {
    content: "";
    display: block;
    position: absolute;
    bottom: 0;
    right: 0;
    width: 2.4em;
    height: 1.5em;
    background: linear-gradient(to right, rgba(255, 255, 255, 0), white 50%);
  }
  .product-grid__price {
    color: #E91E63;
    font-weight: bold;
    letter-spacing: .4px;
  }
  .product-grid__extend-wrapper {
    position: relative;
  }
  .product-grid__extend {
    display: none;
    position: absolute;
    padding: 0 1rem 1rem 1rem;
    margin: .4375rem -1rem 0;
    box-shadow: 0px 0px 0px 1px #eee;
    background: #fff;
    border-radius: 0 0 4px 4px;
  }
  .product-grid__extend:before {
    content: "";
    height: .875rem;
    width: 100%;
    position: absolute;
    top: -.4375rem;
    left: 0;
    background: #fff;
  }
  .product-grid__description {
    font-size: .875em;
    margin-top: .4375rem;
    margin-bottom: 0;
  }
  .product-grid__btn {
    display: inline-block;
    font-size: .875em;
    color: #777;
    background: #eee;
    padding: .5em .625em;
    margin-top: .875rem;
    margin-right: .625rem;
    cursor: pointer;
    border-radius: 4px;
  }
  .product-grid__btn i.fa {
    margin-right: .3125rem;
  }
  .product-g {
    color: #fff;
    background: #E91E63;
  }
  .product-grid__add-to-cart:hover {
    background: #ee4c83;
  }
  .product-grid__view {
    color: #777;
    background: #eee;
  }
  .product-grid__view:hover {
    background: white;
  }

.wrapper2{
  position: absolute;
  left: 65%;
  transform: translate(-50%,-50%);
}
.container{
  position: relative;
  padding: 20px 50px;
}

.input{
  min-width: 500px;
  width: 50%;
  border: 3px solid #111;
  background: transparent;
  padding: 15px 30px;
  border-radius: 50px;
  outline: none;
  font-size: 18px;
  color: #111;
  font-weight: bold;
  letter-spacing: 1px;
}

::-webkit-input-placeholder { /* Chrome/Opera/Safari */
  color: #111;
  font-family: Roboto;
  letter-spacing: 2px;
  text-transform: uppercase;
}
::-moz-placeholder { /* Firefox 19+ */
  color: #111;
}
:-ms-input-placeholder { /* IE 10+ */
  color: #111;
}


</style>


<img src="http://i65.tinypic.com/25s4ho7.png" border="0" alt="Image and video hosting by TinyPic"><br / >
<br / >
{%if error%}
<h3><font color="red"><p style="text-align: center;">{{error}}</p></h3></font>
<br / >
{% endif %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<body>
  <div class="wrapper2">
  <div class="container">
    <form method="POST" action="{% url 'games:search' %}">
      {% csrf_token %}
      <input type="text" class="input" id="search" name = 'search' placeholder="Search Game  Title">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</div>

<div class="wrapper">

 <h2><strong>New Releases:</strong></h2>
	<div class="content">
		<!-- content here -->
		<div class="product-grid product-grid--flexbox">
			<div class="product-grid__wrapper">
				<!-- Product list start here -->

				<!-- Single product -->

        {% for game in games.all %}
        <div class="product-grid__product-wrapper">
					<div class="product-grid__product">
            <div class="product-grid__img-wrapper">
              <a href= "{% url 'games:gameDetails'  game.id%}">
							<img src="{{game.image.url}}" alt="Img" class="product-grid__img" />
              </a>
						</div>
            <span class="product-grid__title"><a href= "{% url 'games:gameDetails'  game.id%}">{{game.title}}</a></span>
						<span class="product-grid__price">${{game.price}}</span>
						<div class="product-grid__extend-wrapper">
							<div class="product-grid__extend">
								<p class="product-grid__description">{{game.summary}}</p>

								<span class="product-grid__btn product-grid__add-to-cart" ><a href= "{% url 'games:purchaseGame'  game.id%}"><i class="fa fa-cart-arrow-down"></i> Buy game<a/></span>
								<span class="product-grid__btn product-grid__view">
                  <a href= "{% url 'games:gameDetails'  game.id%}"><i class="fa fa-eye"></i> View more</span>  <a />
							</div>
            </div>
          </div>
        </div>


        {% endfor %}

			</div>
		</div>
	</div>

</div>

</body>



{% endblock %}

VideoGameMarket/games/templates/games/search.html
{%extends 'base.html'%}

{% block content %}
<style>
.content3 {
    max-width: 80%;
    margin: auto;
}
.wrapper2{
  position: absolute;
  left: 65%;
  transform: translate(-50%,-50%);
}
.container{
  position: relative;
  padding: 20px 50px;
}

.input{
  min-width: 500px;
  width: 50%;
  border: 3px solid #111;
  background: transparent;
  padding: 15px 30px;
  border-radius: 50px;
  outline: none;
  font-size: 18px;
  color: #111;
  font-weight: bold;
  letter-spacing: 1px;
}

::-webkit-input-placeholder { /* Chrome/Opera/Safari */
  color: #111;
  font-family: Roboto;
  letter-spacing: 2px;
  text-transform: uppercase;
}
::-moz-placeholder { /* Firefox 19+ */
  color: #111;
}
:-ms-input-placeholder { /* IE 10+ */
  color: #111;
}

hr {
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 1px;
}

</style>

<img src="http://i65.tinypic.com/25s4ho7.png" border="0" alt="Image and video hosting by TinyPic"><br / >
<br / >

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- <form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}

    <label for="username">Username:</label>

    <input type="text" id="username" name="username">
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <div id="lower">
        <label for="checkbox">forgot password</label>
        <input type="submit" value="Login">
    </div>
</form> -->

<body>
  <div class="wrapper2">
  <div class="container">
    <form method="POST" action="{% url 'games:search' %}">
      {% csrf_token %}
      <input type="text" class="input" id="search" name = 'search' placeholder="Search Game  Title">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</div>
<br />
<br />

<h2>Results for: "{{searchQuery}}"</h2>
{% for game in games %}
<hr>

  <div class = "content3">
    <a href= "{% url 'games:gameDetails'  game.id%}"> <h2>{{game.title}}</h2>  </a>
  <img src="{{game.image.url}}" >
  <br />
  <br />
  <strong> Price:</strong>  ${{game.price}}
  <br />
  <strong> Platform: </strong> {{game.platform}}
  <br />

  <input type = "submit" value ="Buy Game!"/>
  <input type = "submit" value ="Add to cart"/>
  <br />

  </div>
{% endfor %}



{% endblock%}

VideoGameMarket/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>DarkNET</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <!--navigation bar-->
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand"  href="{% url 'home' %}">DarkNET</a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="mynav">
        <ul class="nav navbar-nav navbar-right">
          {%if user.is_authenticated %}
          <a href= "{% url 'games:orderHistory'%}"><li>Order History</a></li>
          <a href= "{% url 'games:accountSettings'%}"><li>Account Settings</a></li>
          <li><a href="#" onClick= "document.getElementById('logout').submit()">Logout</a></li>
          <form id = "logout" method ="POST" action = "{% url 'accounts:logout' %}" >
            {% csrf_token %}
            <input type="hidden">
          </form>
          {% else %}
          <li><a href="{% url 'accounts:signup'%}">Sign Up</a></li>
          <li><a href="{% url 'accounts:login'%}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    {% block content %}
    {% endblock %}
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>